const ME = {
  id: "42",
  name: "The Misson",
  handle: "hal9000",
  bio: null,
  twitter_handle: null,
  github_handle: null,
  location: null,
  initials: "hal",
  avatar_placeholder_color: "#D589AB",
  slack_community_username: null,
  slack_community_user_id: null,
  created_at: 1670912116,
  website_anchor: null,
  website: null,
  username: "2001",
  avatar: "https://upload.wikimedia.org/wikipedia/en/4/45/MatchCut.JPG",
  client_flags: {
    pro_plan_walkthrough_shown: true,
  },
  eligible_for_pro_features: true,
  eligible_for_ai: true,
  eligible_for_gpt4: true,
  eligible_for_developer_hub: true,
  eligible_for_bext: true,
  eligible_for_file_search_beta: true,
  can_use_referral_codes: false,
  eligible_for_ai_citations: true,
  eligible_for_cloud_sync: true,
  eligible_for_application_settings: true,
  can_upgrade_to_pro: false,
  can_manage_billing: true,
  subscription: null,
  stripe_subscription_id: null,
  stripe_subscription_status: null,
  stripe_subscription_interval: null,
  has_running_subscription: true,
  has_payments: true,
  stripe_subscription_canceled_at: null,
  stripe_subscription_current_period_end: null,
  has_active_subscription: true,
  can_cancel_subscription: true,
  can_view_billing: true,
  can_modify_subscription_interval: true,
  any_organization_has_active_subscription: true,
  any_organization_has_running_subscription: true,
  any_organization_has_better_ai: true,
  can_upgrade_to_better_ai: false,
  better_ai_subscription_ids: [],
  email: "hal9000@space",
  has_pro_features: true,
  has_better_ai: true,
  receive_extension_issues_weekly_summary: false,
  has_developer_extensions: true,
  admin: true,
  publishing_bot: true,
  organizations: [],
  swag_info: null,
};

$done({ response: { body: JSON.stringify(ME) } });
